services:
  frontend:
    container_name: chess-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    container_name: chess-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - ./backend/.env
    restart: unless-stopped
    environment:
      BOT_USERNAME: ${BOT_USERNAME}
    depends_on:
      postgresql:
        condition: service_healthy
  chess-bot:
    container_name: chess-bot
    build:
      context: ./chess-bot
      dockerfile: dockerfile
    ports:
      - 8000:8000
    environment:
      BOT_USERNAME: ${BOT_USERNAME}
      BOT_PASSWORD: ${BOT_PASSWORD}
    restart: unless-stopped
    command: uv run fastapi run src/main.py

  postgresql:
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chess
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
