FROM node:lts-alpine

WORKDIR /app

COPY package.json yarn.lock ./

COPY prisma ./prisma

RUN yarn install --frozen-lockfile

RUN npx prisma generate

COPY . .

EXPOSE 3030

CMD ["sh", "-c", "npx prisma migrate deploy && yarn start"]